#!/bin/sh
# Exercise a storage-equipped node serving its map repository to a storage-less
# node over the 802.11s / batman-adv mesh: the "map server for the mesh" role.
#
# Usage: sudo test/bench/map-server-mesh.sh
#
# WHAT THIS IS FOR. TBR-MAP-01 selects the on-node tile store and server. A
# 2026-09-04 real-EUD session (docs/evidence/TBR-MAP-01/) found that provisioning
# is area-scoped by storage -- an AO is tens of MB, a region at street detail is
# hundreds of GB -- so a node carrying a large repository is a map server not
# only for its own EUDs but, acting as a server, for other nodes over the mesh.
# services/map/README.md records that as the map-server-for-the-mesh role and
# names it the same share-a-resource pattern as the WAN gateway (TBR-NET-04,
# CONOPS section 42). That claim had no bench behind it; this is the bench. It is
# the direct analog of wan-gateway-sharing.sh: one node holds a resource, a node
# that does not have it reaches it across the mesh.
#
# WHY IT IS NOT IN CI. Like the other benches here, mac80211_hwsim needs a
# wireless stack a hosted runner does not have. Run it on a development machine
# as root. See docs/dev-machine.md.
#
# THE MECHANISM. MULE-A joins the mesh and serves its z/x/y tile store over
# plain HTTP on its bat0 address -- the z/x/y endpoint services/map/README.md
# commits to. MULE-B joins the same mesh with NO store, and fetches a tile from
# MULE-A across batman-adv. The tile MULE-B receives is compared byte-for-byte
# (md5) against MULE-A's on-disk copy, so a pass proves the repository tile
# itself crossed the mesh -- not that some 200 with some bytes came back.
#
# THE STORE IS BUILT HERE, deterministically, and not committed: a few real
# PNG tiles at plausible z/x/y addresses, generated by a tiny raw-PNG encoder
# (no imagery, no third-party tiles -- committing either would be map data this
# program does not own, and the 2026-09-04 evidence already covers real imagery
# on a real EUD). What this bench adds is the cross-mesh serve, which that one
# did not exercise.
#
# WHAT A PASS RECORDS:
#   1. an 802.11s + batman-adv mesh forms between the two nodes;
#   2. the storage-less node reaches the storage node across it (single-step
#      ping, before anything multi-step is trusted -- CLAUDE.md);
#   3. the storage node serves z/x/y on its mesh address;
#   4. the storage-less node fetches a tile and it is byte-identical to the
#      storage node's stored tile: the repository served across the mesh.
#
# WHAT IT DOES NOT PROVE. hwsim models the 802.11 MAC and nothing physical: no
# propagation, no path loss, no rate adaptation. So no timing or size here is a
# real-radio serve rate, this selects no tile store or server for TBR-MAP-01,
# and it measures no CM4 footprint (TBR-COMP-01). It demonstrates the role and
# the interface, at tier SIMULATED.
#
# RADIO SELECTION IS BY DRIVER, NOT BY NAME. The hwsim radios are taken from the
# mac80211_hwsim device tree under /sys, which by construction cannot name a real
# phy. Selecting mesh radios by a name or mode match once moved a live radio into
# a namespace on this bench host; never match radios by grep. See
# test/flatsat/README.md and CLAUDE.md ("A bench must be configured the way the
# program decided").
set -eu

MESH_ID=fml-mapmesh
FREQ=2412
MTU=1560
SERVE_IP=10.43.0.1
CLIENT_IP=10.43.0.2
PORT=8080
STORE=
SRVPID=/tmp/fml-mapsrv.pid

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}
info() { printf '  %s\n' "$1"; }

cleanup() {
  if [ -f "$SRVPID" ]; then
    kill "$(cat "$SRVPID")" 2>/dev/null || true
    rm -f "$SRVPID"
  fi
  ip netns del mapa 2>/dev/null || true
  ip netns del mapb 2>/dev/null || true
  [ -n "$STORE" ] && rm -rf "$STORE"
  rmmod mac80211_hwsim 2>/dev/null || true
}
trap cleanup EXIT INT TERM

[ "$(id -u)" -eq 0 ] || fail 'must run as root: it loads a module and creates namespaces.'

for tool in ip iw batctl python3 curl md5sum file; do
  command -v "$tool" >/dev/null 2>&1 ||
    fail "$tool is not installed. apt-get install iproute2 iw batctl python3 curl coreutils file"
done

if ! modinfo mac80211_hwsim >/dev/null 2>&1; then
  fail 'mac80211_hwsim is not in this kernel. A hosted runner has no wireless
stack at all; this needs an ordinary distribution kernel.'
fi

# Only phys under the mac80211_hwsim device tree. This cannot name a real phy,
# which is the whole point -- see the header.
hwsim_phys() {
  for d in /sys/devices/virtual/mac80211_hwsim/*/ieee80211/phy*; do
    [ -e "$d" ] && basename "$d"
  done
}

# A deterministic real PNG tile: a tiny raw encoder, no imagery, no PIL. Same
# bytes every run, so the md5 comparison is meaningful and nothing is committed.
make_tile() {
  # $1 output path, $2 seed
  python3 - "$1" "$2" <<'PY'
import struct, sys, zlib
path, seed = sys.argv[1], int(sys.argv[2])
w = h = 256
raw = bytearray()
for y in range(h):
    raw.append(0)  # filter: none
    raw += bytes([(y * 7 + seed) & 255, (y * 13 + seed) & 255, 128]) * w
def chunk(typ, data):
    body = typ + data
    return struct.pack('>I', len(data)) + body + struct.pack('>I', zlib.crc32(body) & 0xffffffff)
png = b'\x89PNG\r\n\x1a\n'
png += chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
png += chunk(b'IDAT', zlib.compress(bytes(raw), 9))
png += chunk(b'IEND', b'')
with open(path, 'wb') as f:
    f.write(png)
PY
}

join() {
  # $1 namespace, $2 last octet
  ns=$1
  oct=$2
  dev=$(ip netns exec "$ns" sh -c 'ls /sys/class/net' | grep '^wlan' | head -1)
  [ -n "$dev" ] || fail "no wlan interface in namespace $ns"
  ip netns exec "$ns" iw dev "$dev" set type mp
  ip netns exec "$ns" ip link set "$dev" mtu "$MTU" up
  ip netns exec "$ns" iw dev "$dev" mesh join "$MESH_ID" freq "$FREQ"
  ip netns exec "$ns" batctl routing_algo BATMAN_IV >/dev/null 2>&1 || true
  ip netns exec "$ns" ip link add name bat0 type batadv
  # bridge_loop_avoidance 0 per FML-ADR-056: default ENABLED stalls traffic ~30s
  # while every batctl table reads correct.
  ip netns exec "$ns" batctl meshif bat0 bridge_loop_avoidance 0 >/dev/null 2>&1 || true
  ip netns exec "$ns" ip link set "$dev" master bat0
  ip netns exec "$ns" ip addr add "10.43.0.$oct/24" dev bat0
  ip netns exec "$ns" ip link set bat0 up
}

# Build MULE-A's tile store: a small z/x/y tree of deterministic tiles.
STORE=$(mktemp -d /tmp/fml-mapstore.XXXXXX)
mkdir -p "$STORE/15/6852" "$STORE/16/13704"
make_tile "$STORE/15/6852/12530.png" 40
make_tile "$STORE/16/13704/25060.png" 90
TILE=15/6852/12530.png
info "MULE-A store built at $STORE ($(find "$STORE" -name '*.png' | wc -l) tiles)"

rmmod mac80211_hwsim 2>/dev/null || true
modprobe mac80211_hwsim radios=2
sleep 1
set --
for p in $(hwsim_phys); do
  set -- "$@" "$p"
done
[ "$#" -ge 2 ] || fail "need >=2 hwsim radios (got $#)"
PHY_A=$1
PHY_B=$2
info "MULE-A radio=$PHY_A (store server), MULE-B radio=$PHY_B (storage-less)"
info "radios chosen from the hwsim device tree; no real phy can be named here"

ip netns add mapa
ip netns add mapb
iw phy "$PHY_A" set netns name mapa
iw phy "$PHY_B" set netns name mapb
sleep 1
join mapa 1
join mapb 2
info "802.11s + batman-adv mesh formed (MULE-A $SERVE_IP, MULE-B $CLIENT_IP)"

# Single-step before multi-step (CLAUDE.md): does the mesh carry a packet at all.
ok=0
for _ in $(seq 1 20); do
  if ip netns exec mapb ping -c2 -W2 "$SERVE_IP" >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 3
done
[ "$ok" -eq 1 ] || fail "mesh did not carry traffic MULE-B -> MULE-A"
info "mesh carries traffic (MULE-B reaches MULE-A)"

# MULE-A serves its store on the mesh.
ip netns exec mapa sh -c "cd '$STORE' && exec python3 -m http.server $PORT --bind $SERVE_IP >/tmp/fml-mapsrv.log 2>&1 & echo \$! > '$SRVPID'"
sleep 3
ip netns exec mapa sh -c "ss -ltn 2>/dev/null | grep -q ':$PORT'" ||
  fail "tile server did not bind $SERVE_IP:$PORT on MULE-A"
info "MULE-A serving z/x/y on the mesh at $SERVE_IP:$PORT"

# MULE-B (no store) fetches a tile across the mesh.
ORIG_MD5=$(md5sum "$STORE/$TILE" | cut -d' ' -f1)
CODE=$(ip netns exec mapb curl -s -o /tmp/fml-fetched.png -w '%{http_code}' \
  "http://$SERVE_IP:$PORT/$TILE")
[ "$CODE" = "200" ] || fail "MULE-B got HTTP $CODE fetching $TILE over the mesh"
GOT_MD5=$(md5sum /tmp/fml-fetched.png | cut -d' ' -f1)
SIZE=$(wc -c </tmp/fml-fetched.png | tr -d ' ')
KIND=$(file -b /tmp/fml-fetched.png | cut -d, -f1)
[ "$GOT_MD5" = "$ORIG_MD5" ] ||
  fail "fetched tile differs from MULE-A's store (md5 $GOT_MD5 != $ORIG_MD5)"
rm -f /tmp/fml-fetched.png

printf '\n'
printf 'PASS. Storage-less MULE-B fetched a map tile from MULE-A over the mesh.\n'
printf '  tile:  %s\n' "$TILE"
printf '  bytes: %s, %s\n' "$SIZE" "$KIND"
printf '  md5:   %s -- byte-identical to MULE-A store; the repository tile\n' "$ORIG_MD5"
printf '         itself crossed 802.11s + batman-adv to the storage-less node.\n'
printf '\n'
printf 'This is the map-server-for-the-mesh role (services/map/README.md): one\n'
printf 'node holds the repository and serves it to the rest of the mesh -- the\n'
printf 'TBR-NET-04 share-a-resource pattern applied to TBR-MAP-01.\n'
printf 'Tier: SIMULATED. hwsim models the 802.11 MAC and nothing physical; no\n'
printf 'serve rate here is a real-radio rate, and this selects no store or server.\n'
