#!/bin/sh
# Generate STATUS.md from the ADR register, the trade register and MAINTAINERS.
#
# Usage: tools/gen-status.sh [--check]
#
#   (no argument)  write STATUS.md
#   --check        write nothing; exit non-zero if the committed STATUS.md
#                  differs from freshly generated output
#
# STATUS.md IS GENERATED AND NEVER HAND-EDITED. A stale status page is how a
# repository signals abandonment, so the committed copy is checked in CI
# against fresh output and the build fails if they differ.

set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

ADR_DIR=docs/adr
TRADE_DIR=docs/trades
OUT=STATUS.md

CHECK=0
if [ $# -gt 0 ]; then
  case "$1" in
    --check) CHECK=1 ;;
    *)
      printf 'Usage: %s [--check]\n' "$0" >&2
      exit 2
      ;;
  esac
fi

frontmatter_field() {
  awk -v field="$2" '
    NR == 1 && $0 == "---" { inside = 1; next }
    inside && $0 == "---" { exit }
    inside {
      idx = index($0, ":")
      if (idx > 0) {
        key = substr($0, 1, idx - 1)
        val = substr($0, idx + 1)
        gsub(/^[ \t]+|[ \t]+$/, "", key)
        gsub(/^[ \t]+|[ \t]+$/, "", val)
        if (key == field) { print val; exit }
      }
    }
  ' "$1"
}

# True when a trade is still outstanding (its dependency is not yet discharged).
# Used to keep the "Open trades it depends on" column of the decisions table
# honest once trades start closing: a CLOSED or ABANDONED trade is no longer an
# open dependency and must not be listed as one. An unknown id is kept, so a
# typo shows up rather than vanishing.
trade_outstanding() {
  for tf in "$TRADE_DIR/$1-"*.md; do
    [ -e "$tf" ] || return 0
    case "$(frontmatter_field "$tf" status)" in
      CLOSED | ABANDONED) return 1 ;;
      *) return 0 ;;
    esac
  done
}

tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.trades" "$tmp.out"' EXIT INT TERM

{
  cat <<'HEADER'
# Status

<!-- DO NOT EDIT. GENERATED FILE. -->

**This file is generated by `tools/gen-status.sh`. Do not edit it by hand.**
Change the frontmatter in `docs/adr/` and `docs/trades/`, or the roles table in
`MAINTAINERS.md`, and regenerate. CI fails if the committed copy differs from
freshly generated output.

Program: FERAL MULE (FML). Deliverable: MULE, Multi-Bearer Utility Link
Equipment.

**Stage: pre-PDR.** The operational concept is baselined, the architecture is
drafted, and almost nothing is built or measured. Nothing in this repository
has been tested. No hardware has been selected. No image has been built.

HEADER

  # --- Decisions ------------------------------------------------------------
  printf '## Decisions\n\n'
  printf 'Identifiers are permanent and never reused. A changed decision is superseded\n'
  printf 'by a new one, never edited in place. See `docs/adr/README.md`.\n\n'

  for status in SELECTED "SELECTED PRINCIPLE" "SELECTED TARGET" \
    "SELECTED PLANNING BASELINE" PREFERRED CONDITIONAL PROPOSED SUPERSEDED RETIRED; do
    rows=''
    for f in "$ADR_DIR"/FML-ADR-*.md; do
      [ -e "$f" ] || continue
      s=$(frontmatter_field "$f" status)
      [ "$s" = "$status" ] || continue
      id=$(frontmatter_field "$f" id)
      title=$(frontmatter_field "$f" title)
      trades=$(frontmatter_field "$f" trades)
      trades=$(printf '%s' "$trades" | sed -e 's/^\[//' -e 's/\]$//' -e 's/,/ /g')
      open_trades=''
      for t in $trades; do
        trade_outstanding "$t" && open_trades="$open_trades$t, "
      done
      open_trades=$(printf '%s' "$open_trades" | sed 's/, $//')
      [ -n "$open_trades" ] || open_trades='none'
      rows="$rows| \`$id\` | $title | $open_trades |
"
    done
    [ -n "$rows" ] || continue
    printf '### %s\n\n' "$status"
    printf '| ID | Decision | Open trades it depends on |\n'
    printf '| --- | --- | --- |\n'
    printf '%s' "$rows"
    printf '\n'
  done

  # --- Trades ---------------------------------------------------------------
  printf '## Open trades\n\n'
  printf 'A trade closes on evidence under `docs/evidence/<TRADE-ID>/`, never on document\n'
  printf 'wording. See `docs/trades/README.md`.\n\n'
  printf 'Ordered by the SAD v0.31 section 30.2 priority.\n\n'
  printf '| Pri | ID | Question | Status | Function owner | Named owner | HW |\n'
  printf '| ---: | --- | --- | --- | --- | --- | --- |\n'

  # Rows are collected into a file first. Counting inside the sort pipeline
  # would put the counters in a subshell and lose them.
  : >"$tmp.trades"
  for f in "$TRADE_DIR"/TBR-*.md; do
    [ -e "$f" ] || continue
    case "$(basename "$f")" in _*) continue ;; esac
    status=$(frontmatter_field "$f" status)
    [ "$status" = "CLOSED" ] && continue
    [ "$status" = "ABANDONED" ] && continue
    id=$(frontmatter_field "$f" id)
    title=$(frontmatter_field "$f" title)
    owner=$(frontmatter_field "$f" owner)
    pri=$(frontmatter_field "$f" priority)
    [ -n "$pri" ] || pri=99
    fowner=$(frontmatter_field "$f" function-owner)
    [ -n "$fowner" ] || fowner=TBD
    hw=$(frontmatter_field "$f" requires-hardware)
    [ -n "$hw" ] || hw=TBD
    printf '%03d|%s|%s|%s|%s|%s|%s\n' \
      "$pri" "$id" "$title" "$status" "$fowner" "$owner" "$hw" >>"$tmp.trades"
  done

  open_count=$(wc -l <"$tmp.trades" | tr -d ' ')
  # A named owner is required by the SAD section 30.2 SRR exit action.
  # TBD-SRR marks the gap explicitly and still counts as unowned.
  unowned=$(awk -F'|' '$6 == "TBD" || $6 ~ /^TBD-/' "$tmp.trades" | wc -l | tr -d ' ')

  sort -n "$tmp.trades" | awk -F'|' '{
    printf "| %d | `%s` | %s | `%s` | %s | `%s` | %s |\n",
      $1, $2, $3, $4, $5, $6, $7
  }'
  printf '\n%s open trades. %s have no named owner.\n\n' "$open_count" "$unowned"

  # --- Critical path --------------------------------------------------------
  printf '## Critical path\n\n'
  cp_rows=''
  for f in "$TRADE_DIR"/TBR-*.md; do
    [ -e "$f" ] || continue
    case "$(basename "$f")" in _*) continue ;; esac
    [ "$(frontmatter_field "$f" critical-path)" = "true" ] || continue
    status=$(frontmatter_field "$f" status)
    [ "$status" = "CLOSED" ] && continue
    id=$(frontmatter_field "$f" id)
    title=$(frontmatter_field "$f" title)
    owner=$(frontmatter_field "$f" owner)
    pri=$(frontmatter_field "$f" priority)
    [ -n "$pri" ] || pri=99
    hw=$(frontmatter_field "$f" requires-hardware)
    cp_rows="$cp_rows$(printf '%03d|%s|%s|%s|%s' "$pri" "$id" "$title" "$owner" "$hw")
"
  done
  if [ -n "$cp_rows" ]; then
    printf 'Marked CRITICAL in the SAD v0.31 body. Ordered by SAD priority.\n\n'
    printf '| Pri | ID | Question | Named owner | HW |\n'
    printf '| ---: | --- | --- | --- | --- |\n'
    printf '%s' "$cp_rows" | grep -v '^$' | sort -n | awk -F'|' '{
      printf "| %d | `%s` | %s | `%s` | %s |\n", $1, $2, $3, $4, $5
    }'
  else
    printf 'No trade is marked critical path.\n'
  fi
  printf '\n'

  # --- Maintainers ----------------------------------------------------------
  printf '## Maintainer roles\n\n'
  printf 'No role may sit with a single name, or with none, for more than 90 days without\n'
  printf 'being raised as a program risk. See `MAINTAINERS.md`.\n\n'
  printf '| Role | Primary | Alternate |\n'
  printf '| --- | --- | --- |\n'

  vacant=0
  roles=0
  # Read the roles table from MAINTAINERS.md: rows with four cells whose header
  # row is "Role | Primary | Alternate | Held since".
  sed -n '/^| Role | Primary | Alternate | Held since |$/,/^$/p' MAINTAINERS.md |
    grep '^| ' | grep -v '^| Role ' | grep -v '^| --- ' >"$tmp" || true
  while IFS= read -r row; do
    [ -n "$row" ] || continue
    role=$(printf '%s' "$row" | awk -F'|' '{gsub(/^ +| +$/,"",$2); print $2}')
    primary=$(printf '%s' "$row" | awk -F'|' '{gsub(/^ +| +$/,"",$3); print $3}')
    alternate=$(printf '%s' "$row" | awk -F'|' '{gsub(/^ +| +$/,"",$4); print $4}')
    [ -n "$role" ] || continue
    roles=$((roles + 1))
    [ "$primary" = "VACANT" ] && vacant=$((vacant + 1))
    [ "$alternate" = "VACANT" ] && vacant=$((vacant + 1))
    printf '| %s | %s | %s |\n' "$role" "$primary" "$alternate"
  done <"$tmp"
  printf '\n%s vacant slots across %s roles.\n\n' "$vacant" "$roles"

  # --- Program risks --------------------------------------------------------
  printf '## Reported risks\n\n'
  risks=0
  if [ "$vacant" -gt 0 ]; then
    risks=$((risks + 1))
    printf -- '- **%s vacant maintainer slots.** A role with no name is a role nobody\n' "$vacant"
    printf '  answers for. See `MAINTAINERS.md`.\n'
  fi
  for f in "$TRADE_DIR"/TBR-*.md; do
    [ -e "$f" ] || continue
    case "$(basename "$f")" in _*) continue ;; esac
    [ "$(frontmatter_field "$f" critical-path)" = "true" ] || continue
    case "$(frontmatter_field "$f" owner)" in TBD | TBD-*) ;; *) continue ;; esac
    [ "$(frontmatter_field "$f" status)" = "CLOSED" ] && continue
    risks=$((risks + 1))
    id=$(frontmatter_field "$f" id)
    printf -- '- **`%s` is CRITICAL and has no named owner.** Assigning a named\n' "$id"
    printf '  individual and a target date to every open TBR is an SRR exit action\n'
    printf '  (SAD section 30.2). A trade cannot close while nobody can accept its\n'
    printf '  evidence.\n'
  done
  [ "$risks" -eq 0 ] && printf 'None reported.\n'
  printf '\n'

  printf -- '---\n\n'
  printf 'Generated by `tools/gen-status.sh` from `docs/adr/`, `docs/trades/` and\n'
  printf '`MAINTAINERS.md`. Do not edit this file.\n'
} >"$tmp.out"

if [ "$CHECK" -eq 1 ]; then
  if [ ! -f "$OUT" ]; then
    printf 'FAIL: %s does not exist. Run tools/gen-status.sh.\n' "$OUT" >&2
    rm -f "$tmp.out"
    exit 1
  fi
  if ! diff -u "$OUT" "$tmp.out" >/dev/null 2>&1; then
    printf 'FAIL: %s differs from freshly generated output.\n' "$OUT" >&2
    printf 'STATUS.md is generated and never hand-edited. Run tools/gen-status.sh\n' >&2
    printf 'and commit the result.\n\n' >&2
    diff -u "$OUT" "$tmp.out" >&2 || true
    rm -f "$tmp.out"
    exit 1
  fi
  rm -f "$tmp.out"
  printf '%s is up to date.\n' "$OUT"
  exit 0
fi

mv "$tmp.out" "$OUT"
printf 'Wrote %s\n' "$OUT"
