#!/bin/sh
# Generate the requirement traceability matrix.
#
# Usage: tools/gen-traceability.sh [--check] [--out PATH]
#
#   (no argument)  write the matrix to docs/verification/traceability.md
#   --check        write nothing; exit non-zero if any binding requirement
#                  lacks an architecture allocation or a validating stage
#
# TRACEABILITY IS A BUILD ARTIFACT, NOT A DOCUMENT SOMEONE MAINTAINS.
#
# Hand-extracted traceability has already failed once in this program's
# history, at a smaller scale than the program now operates at. This script
# exists so that it is not recreated by hand at a larger one.
#
# THE CHAIN
#
#   operational requirement (CONOPS)
#     -> architecture allocation (component or ADR)
#       -> validating test stage (test/stages/)
#
# A REQUIREMENT WITH NO VALIDATING STAGE IS A DEFECT. Not a gap to be filled
# later: a defect, which --check fails the build for. A requirement nobody can
# test is a requirement nobody can be wrong about, and it will be declared
# satisfied at the end of the program by whoever is most tired.
#
# The same applies to a binding requirement with no allocation. If no component
# owns it, nothing implements it.
#
# SOURCE FORMAT
#
# Requirement-bearing documents carry frontmatter:
#
#   ---
#   requirements:
#     - id: FML-REQ-001
#       source: CONOPS 3.2
#       modal: shall
#       text: The node shall retain local time across power loss.
#       allocation: FML-ADR-042
#       stage: STAGE-2
#   ---
#
# Only `modal: shall` is binding. `should` is preferred and waiverable; `may`
# creates no obligation. See CONTRIBUTING.md.
#
# THE REQUIREMENT SET IS NOT YET POPULATED, because the CONOPS has not been
# transcribed. This generator and its check are wired up anyway, so that the
# first requirement to land arrives into working machinery rather than into a
# promise that machinery will be built.

set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

OUT=docs/verification/traceability.md
CHECK=0

while [ $# -gt 0 ]; do
  case "$1" in
    --check)
      CHECK=1
      shift
      ;;
    --out)
      OUT=${2:?--out needs a path}
      shift 2
      ;;
    *)
      printf 'Usage: %s [--check] [--out PATH]\n' "$0" >&2
      exit 2
      ;;
  esac
done

tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.body"' EXIT INT TERM

# Extract requirement records from the frontmatter of every Markdown file under
# docs/. Emits one tab-separated record per requirement:
#   id  source  modal  allocation  stage  file  text
# LC_ALL=C: this feeds a generated, drift-checked file, and sort order is
# locale-dependent. See the note in tools/gen-decision-index.sh.
find docs -name '*.md' -type f 2>/dev/null | LC_ALL=C sort | while IFS= read -r f; do
  awk -v file="$f" '
    function flush() {
      if (id != "") {
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
          id, (source == "" ? "TBD" : source), (modal == "" ? "TBD" : modal),
          (allocation == "" ? "" : allocation), (stage == "" ? "" : stage),
          file, (text == "" ? "TBD" : text)
      }
      id = ""; source = ""; modal = ""; allocation = ""; stage = ""; text = ""
    }
    NR == 1 && $0 == "---" { fm = 1; next }
    fm && $0 == "---" { flush(); exit }
    !fm { exit }
    fm && /^requirements:[[:space:]]*$/ { inreq = 1; next }
    fm && inreq && /^[a-zA-Z_-]+:/ { flush(); inreq = 0; next }
    fm && inreq {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      if (substr(line, 1, 2) == "- ") { flush(); line = substr(line, 3) }
      idx = index(line, ":")
      if (idx == 0) next
      key = substr(line, 1, idx - 1)
      val = substr(line, idx + 1)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
      gsub(/^"|"$/, "", val)
      if (key == "id") id = val
      else if (key == "source") source = val
      else if (key == "modal") modal = val
      else if (key == "allocation") allocation = val
      else if (key == "stage") stage = val
      else if (key == "text") text = val
    }
  ' "$f"
done >"$tmp"

total=$(wc -l <"$tmp" | tr -d ' ')
binding=$(awk -F'\t' '$3 == "shall"' "$tmp" | wc -l | tr -d ' ')
defects=$(awk -F'\t' '$3 == "shall" && ($4 == "" || $5 == "")' "$tmp" | wc -l | tr -d ' ')

if [ "$CHECK" -eq 1 ]; then
  if [ "$defects" -gt 0 ]; then
    printf 'FAIL: %s binding requirement(s) lack an allocation or a validating stage.\n\n' "$defects" >&2
    awk -F'\t' '$3 == "shall" && ($4 == "" || $5 == "") {
      printf "  %s (%s)\n", $1, $6
      if ($4 == "") printf "    no architecture allocation\n"
      if ($5 == "") printf "    no validating stage\n"
    }' "$tmp" >&2
    printf '\nA requirement with no validating stage is a defect. See\n' >&2
    printf 'docs/verification/README.md.\n' >&2
    exit 1
  fi
  printf 'Traceability: %s requirement(s), %s binding, 0 defects.\n' "$total" "$binding"
  exit 0
fi

{
  cat <<'HEADER'
# Traceability matrix

<!-- DO NOT EDIT. GENERATED FILE. -->

**Generated by `tools/gen-traceability.sh`. Do not edit by hand.** Change the
requirement frontmatter in the source documents and regenerate.

Traceability runs from an operational requirement, to an architecture
allocation, to a validating test stage. **A binding requirement with no
allocation or no validating stage is a defect**, and
`tools/gen-traceability.sh --check` fails the build for it.

Only `shall` is binding. `should` is preferred and waiverable with recorded
rationale; `may` creates no obligation. See `CONTRIBUTING.md`.

HEADER

  printf '## Summary\n\n'
  printf '| Metric | Count |\n'
  printf '| --- | --- |\n'
  printf '| Requirements | %s |\n' "$total"
  printf '| Binding (`shall`) | %s |\n' "$binding"
  printf '| Defects | %s |\n' "$defects"
  printf '\n'

  if [ "$total" -eq 0 ]; then
    cat <<'EMPTY'
## Matrix

**The requirement set is not yet populated.**

The CONOPS is baselined but has not been transcribed into this repository; see
`docs/conops/README.md`. Until it is, there are no requirements to trace, and
several open trades are blocked less by hardware than by the absence of a
stated requirement from it.

This generator and its CI check are wired up regardless, so that the first
requirement to land arrives into working machinery rather than into a promise
that machinery will be built. Hand-extracted traceability has already failed
once in this program's history; recreating it by hand at a larger scale would
fail again, later, and more expensively.
EMPTY
    printf '\n'
  else
    printf '## Matrix\n\n'
    printf '| Requirement | Source | Modal | Allocation | Stage | Document |\n'
    printf '| --- | --- | --- | --- | --- | --- |\n'
    awk -F'\t' '{
      alloc = ($4 == "" ? "**MISSING**" : "`" $4 "`")
      stage = ($5 == "" ? "**MISSING**" : "`" $5 "`")
      printf "| `%s` | %s | `%s` | %s | %s | `%s` |\n", $1, $2, $3, alloc, stage, $6
    }' "$tmp"
    printf '\n'
    if [ "$defects" -gt 0 ]; then
      printf '## Defects\n\n'
      printf '%s binding requirement(s) lack an allocation or a validating stage.\n\n' "$defects"
      awk -F'\t' '$3 == "shall" && ($4 == "" || $5 == "") {
        printf "- `%s` in `%s`:", $1, $6
        if ($4 == "") printf " no architecture allocation."
        if ($5 == "") printf " no validating stage."
        printf "\n"
      }' "$tmp"
      printf '\n'
    fi
  fi

  printf -- '---\n\n'
  printf 'Generated by `tools/gen-traceability.sh`. Do not edit this file.\n'
} >"$tmp.body"

mkdir -p "$(dirname "$OUT")"
mv "$tmp.body" "$OUT"
printf 'Wrote %s: %s requirement(s), %s binding, %s defect(s).\n' \
  "$OUT" "$total" "$binding" "$defects"
